/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author User
 */
public class transaksi extends javax.swing.JFrame {
public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabmodel;
    Connection cn = config.koneksi.getkoneksi();
    public long bayarr;
    public long totall;
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        barang();
        jual();
        tampiltmp();
        judul();
        reset();
        transaksi();
      
        kd_transaksi.setEnabled(false);
        kd_barang.setEnabled(false);
        kembali.setEnabled(false);
        harga.setEnabled(false);
        stok.setEnabled(false);
        tambah.setEnabled(false);
        jButton3.setEnabled(false);
        
    }
    private void tampiltmp(){
        try {
            st = cn.createStatement();
            tabmodel.getDataVector().removeAllElements();
            tabmodel.fireTableDataChanged();
            rs = st.executeQuery("select * from tb_keranjang");
            while (rs.next()){
                Object[] data = {
                    rs.getString("kd_tmp"),
                    rs.getString("kd_barang"),
                    rs.getString("qty"),
                    rs.getString("sub_total")
                };
                tabmodel.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
     public void judul(){
        Object[] judul = {"kd tmp","kd barang","qty","sub_total"};
        tabmodel = new DefaultTableModel(null, judul);
        tbl_tmp.setModel(tabmodel);
    }
     private void reset(){
         nama_barang.setSelectedItem(null);
         kd_barang.setText("");
         harga.setText("");
         stok.setText("");
         qty.setText("");
         sub_total.setText("0");
     }
     private void jual(){ 
        try{
            Random angka = new Random();
            String angkaa = String.valueOf(angka.nextInt(999));
            String kode = "T"+angkaa;
            kd_tmp.setText(kode);
            kd_tmp.setEnabled(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
private void transaksi(){ 
        try{
            java.util.Date tgl = new java.util.Date();
            java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyMMdd");
            java.text.SimpleDateFormat tanggal = new java.text.SimpleDateFormat("yyyyMMdd");
            
            String sql = "Select max(kd_transaksi) from tb_transaksi where tanggal =" + tanggal.format(tgl);
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                Long a = rs.getLong(1);
                if (a == 0) {
                    this.kd_transaksi.setText(kal.format(tgl)+"0000"+(a+1));
                } else {
                    this.kd_transaksi.setText(""+(a+1));
                }
            }
            
//            Random angka = new Random();
//            String angkaa = String.valueOf(angka.nextInt(999));
//            String kode = "MB"+angkaa;
//            kd_transaksi.setText(kode);
//            kd_transaksi .setEnabled(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

 public void barang(){
        nama_barang.removeAllItems();
        nama_barang.addItem("Pilih Buku");
        try {
            st = cn.createStatement();
            rs = st.executeQuery("select * from tb_barang");
            while (rs.next()) {
                nama_barang.addItem(rs.getString("nama_barang"));
            }
        } catch (Exception e) { 
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nama_barang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kd_tmp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sub_total = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tmp = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kembali = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kd_transaksi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        no_telp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        kd_barang = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("BELI BARANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel14)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("sub total");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 90, -1));

        nama_barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nama_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_barangActionPerformed(evt);
            }
        });
        getContentPane().add(nama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 190, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Barang");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, -1));
        getContentPane().add(stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 190, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("kd barang ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 90, -1));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 190, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Kode Transaksi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 120, 20));
        getContentPane().add(kd_tmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 50, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Stok");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, -1));

        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 190, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("qty");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 90, -1));

        sub_total.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sub_total.setText("jLabel7");
        sub_total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sub_totalKeyTyped(evt);
            }
        });
        getContentPane().add(sub_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 120, 20));

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 110, 40));

        tbl_tmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_tmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tmp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 340, 130));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("TOTAL ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 80, 20));

        total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total.setText("TOTAL");
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Kembali");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 50, 20));

        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, 200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("kode jual");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 20));

        kd_transaksi.setEditable(false);
        getContentPane().add(kd_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 160, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Nama ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 50, 14));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 200, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("no telp");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 50, 14));
        getContentPane().add(no_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 200, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Alamat");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 50, 14));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Bayar");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 50, 14));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 200, 30));

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bayarKeyTyped(evt);
            }
        });
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 200, 30));

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 80, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Ok_48px.png"))); // NOI18N
        jButton3.setText("SELESAI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 150, 50));

        jButton4.setText("Hitung");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 80, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Harga");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, -1));

        kd_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kd_barangActionPerformed(evt);
            }
        });
        getContentPane().add(kd_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 190, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Left_50px.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 60, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nama_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_barangActionPerformed
        // TODO add your handling code here:
        try {
            harga.setText("");
            stok.setText("");
            st = cn.createStatement();
            rs = st.executeQuery("select * from tb_barang where nama_barang = '"+ nama_barang.getSelectedItem() +"'");
            while (rs.next()) {                
                if ("Pilih Barang".equals(nama_barang.getSelectedItem())) {
                    harga.setText("");
                    stok.setText("");
                } else {
                    kd_barang.setText(rs.getString("kd_barang"));
                   harga.setText(rs.getString("harga"));
                   stok.setText(rs.getString("stok"));

                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_nama_barangActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here
          if("".equals(qty.getText())){
            JOptionPane.showMessageDialog(null, "Lengkapi data!");
        }else{
             try {
            st=cn.createStatement();
            st.executeUpdate("insert into tb_keranjang set " + "kd_tmp = '" + kd_tmp.getText() + "', kd_barang='" + kd_barang.getText()+ "', qty = '" + qty.getText() + "',sub_total = '"+sub_total.getText()+"';");
                 tampiltmp();
                 reset();
                 jual();
            
            int total = 0;
                 for (int i = 0; i < tbl_tmp.getRowCount(); i++) {
                     int amount = Integer.parseInt((String)tbl_tmp.getValueAt(i, 3));
                     total += amount;
                 }
                 this.total.setText("" + total);
                 
            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_qtyKeyTyped

    private void sub_totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sub_totalKeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_sub_totalKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if("".equals(kd_barang.getText())||"".equals(harga.getText())||"".equals(stok.getText()) ||"".equals(qty.getText())){
            JOptionPane.showMessageDialog(null, "lengkapi data");
        }else{
            Integer jumlah = Integer.parseInt(qty.getText());
            Integer stok = Integer.parseInt(this.stok.getText());
            if (jumlah > stok){
                JOptionPane.showMessageDialog(null, "Stok hanya ada "+stok);
            }else{
                int a = Integer.parseInt(harga.getText());
        int b = Integer.parseInt(qty.getText());
        int hitung = a * b;
        sub_total.setText(""+hitung);
        tambah.setEnabled(true);
        jButton3.setEnabled(true);
            }   
        
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tbl_tmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tmpMouseClicked
        // TODO add your handling code here:
         kd_tmp.setText(tabmodel.getValueAt(tbl_tmp.getSelectedRow(), 0) + "");
        kd_barang.setText(tabmodel.getValueAt(tbl_tmp.getSelectedRow(), 1)+ "");
         qty.setText(tabmodel.getValueAt(tbl_tmp.getSelectedRow(), 2)+ "");
        sub_total.setText(tabmodel.getValueAt(tbl_tmp.getSelectedRow(),3) + "");
        
    }//GEN-LAST:event_tbl_tmpMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        tampiltmp();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
                int jawab;
                if ((jawab=JOptionPane.showConfirmDialog(null,"Hapus ?","konfirmasi",JOptionPane.YES_NO_OPTION))==0) {
                    st.executeUpdate("delete from tb_barang where "+"kd_barang='"+tabmodel.getValueAt(tbl_tmp.getSelectedRow(),0)+"'");
                    tampiltmp();
                    reset();
                    JOptionPane.showMessageDialog(null, "Berhasil dihapus");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal diHapus! "+e.getMessage());
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try{
             DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
	           LocalDateTime now = LocalDateTime.now();
            int total = 0;
            st = cn.createStatement();
            rs = st.executeQuery("select * from tb_keranjang");
            while (rs.next()) {
                total = total + Integer.parseInt(rs.getString("sub_total"));
            }
          bayarr = Integer.parseInt(bayar.getText());
         totall = Integer.parseInt(this.total.getText());
            if(bayarr < totall) {
                JOptionPane.showMessageDialog(null, "uang anda kuurang");
            }else{
         
            int kmbl = Integer.parseInt(bayar.getText()) - total;
            st.executeUpdate("insert into tb_transaksi values('"+kd_transaksi.getText()+"','"+nama.getText()+"','"+no_telp.getText()+"','"+alamat.getText()+"','"+total+"','"+Integer.parseInt(bayar.getText())+"','"+kembali.getText()+"','"+now+"')");
            try {
                Desktop.getDesktop().browse(new URL("http://localhost:81/laporan/struk.php?id="+kd_transaksi.getText()).toURI());
            } catch (IOException ex) {
                Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
            } catch (URISyntaxException ex) {
                Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            try {
            int jawab = 0;
            if ((jawab = JOptionPane.showConfirmDialog(null, "Yakin ingin menghari belanja?", "Konfirmasi", JOptionPane.YES_NO_OPTION))==0) {
                String sql = "Truncate tb_keranjang";
            st = cn.createStatement();
            st.executeUpdate(sql);
            tampiltmp();
            transaksi();
            nama.setText("");
            this.total.getText();
            alamat.setText("");
            no_telp.setText("");
            bayar.setText("");
            kembali.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void bayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyTyped
        
    }//GEN-LAST:event_bayarKeyTyped

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        int kmbl = 0;
        kmbl = Integer.parseInt(bayar.getText())-Integer.parseInt(total.getText());
        kembali.setText(String.valueOf(kmbl));
    }//GEN-LAST:event_bayarKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Menu barang = new Menu();
        barang.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void kd_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kd_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kd_barangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kd_barang;
    private javax.swing.JTextField kd_tmp;
    private javax.swing.JTextField kd_transaksi;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField nama;
    private javax.swing.JComboBox<String> nama_barang;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField stok;
    private javax.swing.JLabel sub_total;
    private javax.swing.JButton tambah;
    private javax.swing.JTable tbl_tmp;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
